from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import click

from sdlc_orchestrator.state_machine import WorkflowState
from sdlc_orchestrator.memory import MemoryManager
from sdlc_orchestrator.utils import sdlc_home
from sdlc_orchestrator.commands import console, require_project


@click.group()
def github():
    """GitHub operations. Called by Claude during /sdlc-orchestrate."""
    pass


def _get_repo(project_dir: Path) -> str:
    repo = MemoryManager(project_dir).spec().get("repo", "")
    if not repo:
        click.echo("No repo in spec.yaml", err=True)
        sys.exit(1)
    return repo


@github.command("create-pr")
@click.argument("branch")
@click.argument("phase")
def github_create_pr(branch, phase):
    """Create a GitHub PR for the current phase branch."""
    from sdlc_orchestrator.integrations import github as gh_mod
    from sdlc_orchestrator.integrations.github import create_pr

    project_dir = require_project()
    repo = _get_repo(project_dir)
    spec = MemoryManager(project_dir).spec()
    project_name = spec.get("project_name", project_dir.name)
    subprocess.run(["git", "push", "-u", "origin", branch], cwd=project_dir, capture_output=True)

    wf = WorkflowState(project_dir)
    closes: list[int] = []
    story_item = wf.github_story_items.get(phase, {})
    if story_item.get("number"):
        closes.append(story_item["number"])

    plan_path = project_dir / "docs/sdlc/plan.md"
    if plan_path.exists():
        for s in gh_mod.parse_plan_stories(plan_path.read_text()):
            if s["id"] == phase:
                for task_id in s["task_ids"]:
                    t = wf.github_task_items.get(task_id, {})
                    if t.get("number"):
                        closes.append(t["number"])
                break

    from sdlc_orchestrator.utils import get_active_project
    active = get_active_project(project_dir)
    default_base = f"worktree/{active}" if active else "main"

    url = create_pr(
        repo=repo, phase=phase, branch=branch,
        project_name=project_name,
        base=wf._data.get("base_branch", default_base),
        body=(
            f"## SDLC Phase: `{phase}`\n\n"
            f"Automated output. Review then approve.\n\n"
            f"> Generated by /sdlc-orchestrate"
        ),
        closes_issues=closes,
    )
    click.echo(url or "PR creation skipped (may already exist)")


@github.command("create-issue")
@click.argument("title")
@click.argument("body_file", required=False)
def github_create_issue(title, body_file):
    """Create a GitHub issue. Body read from file or stdin."""
    from sdlc_orchestrator.integrations.github import create_child_issue

    project_dir = require_project()
    repo = _get_repo(project_dir)

    if body_file and Path(body_file).exists():
        body = Path(body_file).read_text()
    elif not sys.stdin.isatty():
        body = sys.stdin.read()
    else:
        body = title

    issue_num = create_child_issue(repo, title, body)
    click.echo(f"issue: {issue_num or 'failed'}")


@github.command("pr-status")
@click.argument("branch")
def github_pr_status(branch):
    """Check if the PR for a branch is approved or merged."""
    from sdlc_orchestrator.integrations.github import get_pr_status

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("no-repo")
        sys.exit(0)

    click.echo(get_pr_status(repo, branch) or "not-found")


@github.command("ingest-feedback")
@click.argument("branch")
@click.argument("phase")
def github_ingest_feedback(branch, phase):
    """Pull PR review comments into .sdlc/feedback/<phase>.md."""
    from sdlc_orchestrator.integrations.github import pull_pr_feedback

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("skipped: no repo configured")
        return

    count = pull_pr_feedback(repo, branch, sdlc_home(project_dir) / "feedback", phase)
    click.echo(f"ingested: {count} comment(s) → .sdlc/feedback/{phase}.md")


@github.command("setup")
def github_setup():
    """Full GitHub setup: labels, project board, workflows, and pre-plan story issues."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")

    if not repo:
        console.print("[red]No repo in spec.yaml — set repo: owner/repo first.[/red]")
        sys.exit(1)
    if not gh.is_available():
        console.print("[red]gh CLI not found or not authenticated.[/red]")
        sys.exit(1)

    project_name = spec.get("project_name", project_dir.name)
    wf = WorkflowState(project_dir)

    # Labels
    console.print("  Creating labels...")
    created = gh.setup_labels(repo)
    console.print(f"  [green]✓[/green] {len(created)} label(s) ready")

    # Project board
    project_info = wf.github_project
    if project_info:
        console.print(f"  [dim]Board #{project_info.get('number')} already exists — skipped[/dim]")
    else:
        console.print("  Creating project board...")
        project_info = gh.create_project_board(project_name, repo)
        if not project_info:
            console.print("  [yellow]Project board creation failed — check gh auth scope (project).[/yellow]")
        else:
            wf.set_github_project(project_info)
            wf.save()
            console.print(
                f"  [green]✓[/green] Board #{project_info['number']} · "
                f"{len(project_info.get('status_options', {}))} status columns"
            )

    # Workflow automations
    if project_info and project_info.get("node_id"):
        console.print("  Enabling workflow automations...")
        enabled = gh.enable_project_workflows(project_info["node_id"])
        if enabled:
            console.print(f"  [green]✓[/green] Workflows: {', '.join(enabled)}")
        else:
            console.print("  [dim]Workflows may already be enabled or require manual setup in GitHub UI.[/dim]")

    # Pre-plan story issues (requirement, design, planning) — created once at setup
    existing = wf.github_story_items
    pre_plan_phases = {"requirement", "design", "planning"}
    if any(p in existing for p in pre_plan_phases):
        console.print("  [dim]Pre-plan story issues already exist — skipped[/dim]")
    else:
        console.print("  Creating pre-plan story issues (requirement, design, planning)...")
        try:
            created_stories = gh.create_pre_plan_story_issues(repo, project_name, project_info)
            if created_stories:
                wf.set_story_items(created_stories)
                for phase, info in created_stories.items():
                    console.print(f"  [green]✓[/green] #{info['number']} {phase}")
            else:
                console.print("  [yellow]Pre-plan story issue creation failed — continuing (local state will be used)[/yellow]")
        except Exception as e:
            console.print(f"  [yellow]Pre-plan story issues skipped: {e}[/yellow]")

    console.print("\n[bold green]GitHub setup complete.[/bold green]")
    if project_info:
        console.print(
            f"  Board: https://github.com/orgs/{repo.split('/')[0]}/projects/{project_info['number']}"
        )


@github.command("sync-board")
def github_sync_board():
    """Move the active story issue to the correct board column based on current state."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)
    project_info = wf.github_project

    if not repo or not project_info:
        click.echo("skipped: no repo or project board configured")
        return

    # Close issues for merged story PRs
    closed = gh.close_merged_pr_issues(
        repo=repo,
        story_items=wf.github_story_items,
        task_items=wf.github_task_items,
        project_info=project_info,
    )
    if closed:
        click.echo(f"auto-closed merged stories: {', '.join(closed)}")

    state_val = wf.state.value

    if state_val == "done":
        for story_id, item in wf.github_story_items.items():
            item_id = item.get("item_id", "")
            if item_id:
                gh._move_item(project_info, item_id, "Done")
            issue_number = item.get("number")
            if issue_number:
                gh.close_issue(repo, issue_number, comment=f"Closed automatically — {story_id} complete.")
        for task_id, item in wf.github_task_items.items():
            issue_number = item.get("number")
            if issue_number:
                gh.close_issue(repo, issue_number, comment=f"Closed automatically — {task_id} complete.")
        click.echo("synced: all stories → Done, issues closed")
        return

    if state_val not in ("story_in_progress", "story_awaiting_review"):
        click.echo(f"skipped: no story board action for state {state_val}")
        return

    story_status = "In Progress" if state_val == "story_in_progress" else "Awaiting Review"
    current = wf.current_story
    if not current:
        click.echo("skipped: no current_story set")
        return

    item = wf.github_story_items.get(current, {})
    item_id = item.get("item_id", "")
    issue_number = item.get("number")

    # Add to board if not already there
    if not item_id and issue_number:
        node_id = gh._get_issue_node_id(repo, issue_number)
        if node_id:
            item_id = gh.add_to_project(project_info["node_id"], node_id)
            if item_id:
                wf.set_story_items({current: {"number": issue_number, "item_id": item_id}})

    if not item_id:
        click.echo(f"skipped: no board item for {current}")
        return

    ok = gh._move_item(project_info, item_id, story_status)
    click.echo(f"{'synced' if ok else 'failed'}: {current} → {story_status}")


@github.command("close-merged")
def github_close_merged():
    """Close story + task issues whose PR branch is merged."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    closed = gh.close_merged_pr_issues(
        repo=repo,
        story_items=wf.github_story_items,
        task_items=wf.github_task_items,
        project_info=wf.github_project,
    )
    click.echo(f"closed: {', '.join(closed)}" if closed else "no merged story PRs found")


@github.command("create-task-issues")
@click.argument("plan_file", default="docs/sdlc/plan.md")
def github_create_task_issues(plan_file):
    """Parse plan.md and create one GitHub issue per task, added to the board."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    plan_path = project_dir / plan_file
    if not plan_path.exists():
        click.echo(f"error: plan file not found at {plan_file}", err=True)
        sys.exit(1)

    tasks = gh.parse_plan_tasks(plan_path.read_text())
    if not tasks:
        click.echo("no tasks found in plan.md")
        return

    new_tasks = [t for t in tasks if t["id"] not in wf.github_task_items]
    if not new_tasks:
        click.echo(f"all {len(tasks)} task issues already exist")
        return

    console.print(f"  Creating {len(new_tasks)} task issue(s)...")
    created = gh.create_task_issues(
        repo=repo, tasks=new_tasks,
        project_info=wf.github_project,
        epic_issue=wf.github_epic_issue,
    )
    wf.set_task_items(created)
    for task_id, info in created.items():
        console.print(f"  [green]✓[/green] #{info['number']} {task_id}")
    click.echo(f"created: {len(created)} issue(s)")


@github.command("create-story-issues")
@click.argument("plan_file", default="docs/sdlc/plan.md")
def github_create_story_issues(plan_file):
    """Parse plan.md and create one GitHub issue per STORY-NNN, added to the board."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    plan_path = project_dir / plan_file
    if not plan_path.exists():
        click.echo(f"error: plan file not found at {plan_file}", err=True)
        sys.exit(1)

    stories = gh.parse_plan_stories(plan_path.read_text())
    if not stories:
        click.echo("no stories found in plan.md (add # STORY-NNN: Title sections)")
        return

    new_stories = [s for s in stories if s["id"] not in wf.github_story_items]
    if not new_stories:
        click.echo(f"all {len(stories)} story issues already exist")
        return

    console.print(f"  Creating {len(new_stories)} story issue(s)...")
    created = gh.create_story_issues(
        repo=repo, stories=new_stories,
        project_info=wf.github_project,
        epic_issue=wf.github_epic_issue,
        task_issue_map=wf.github_task_items,
    )
    wf.set_story_items(created)
    for story_id, info in created.items():
        console.print(f"  [green]✓[/green] #{info['number']} {story_id}")
    click.echo(f"created: {len(created)} story issue(s)")



