from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import click

from sdlc_orchestrator.state_machine import WorkflowState
from sdlc_orchestrator.memory import MemoryManager
from sdlc_orchestrator.utils import sdlc_home
from sdlc_orchestrator.commands import console, require_project


@click.group()
def github():
    """GitHub operations. Called by Claude during /sdlc-orchestrate."""
    pass


def _get_repo(project_dir: Path) -> str:
    repo = MemoryManager(project_dir).spec().get("repo", "")
    if not repo:
        click.echo("No repo in spec.yaml", err=True)
        sys.exit(1)
    return repo


@github.command("create-pr")
@click.argument("branch")
@click.argument("phase")
def github_create_pr(branch, phase):
    """Create a GitHub PR for the current phase branch."""
    from sdlc_orchestrator.integrations import github as gh_mod
    from sdlc_orchestrator.integrations.github import create_pr

    project_dir = require_project()
    repo = _get_repo(project_dir)
    subprocess.run(["git", "push", "-u", "origin", branch], cwd=project_dir, capture_output=True)

    wf = WorkflowState(project_dir)
    closes: list[int] = []
    story_item = wf.github_story_items.get(phase, {})
    if story_item.get("number"):
        closes.append(story_item["number"])

    plan_path = project_dir / "docs/sdlc/plan.md"
    if plan_path.exists():
        for s in gh_mod.parse_plan_stories(plan_path.read_text()):
            if s["id"] == phase:
                for task_id in s["task_ids"]:
                    t = wf.github_task_items.get(task_id, {})
                    if t.get("number"):
                        closes.append(t["number"])
                break

    url = create_pr(
        repo=repo, phase=phase, branch=branch,
        body=(
            f"## SDLC Phase: `{phase}`\n\n"
            f"Automated output. Review then approve.\n\n"
            f"> Generated by /sdlc-orchestrate"
        ),
        closes_issues=closes,
    )
    click.echo(url or "PR creation skipped (may already exist)")


@github.command("create-issue")
@click.argument("title")
@click.argument("body_file", required=False)
def github_create_issue(title, body_file):
    """Create a GitHub issue. Body read from file or stdin."""
    from sdlc_orchestrator.integrations.github import create_child_issue

    project_dir = require_project()
    repo = _get_repo(project_dir)

    if body_file and Path(body_file).exists():
        body = Path(body_file).read_text()
    elif not sys.stdin.isatty():
        body = sys.stdin.read()
    else:
        body = title

    issue_num = create_child_issue(repo, title, body)
    click.echo(f"issue: {issue_num or 'failed'}")


@github.command("pr-status")
@click.argument("branch")
def github_pr_status(branch):
    """Check if the PR for a branch is approved or merged."""
    from sdlc_orchestrator.integrations.github import get_pr_status

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("no-repo")
        sys.exit(0)

    click.echo(get_pr_status(repo, branch) or "not-found")


@github.command("ingest-feedback")
@click.argument("branch")
@click.argument("phase")
def github_ingest_feedback(branch, phase):
    """Pull PR review comments into .sdlc/feedback/<phase>.md."""
    from sdlc_orchestrator.integrations.github import pull_pr_feedback

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("skipped: no repo configured")
        return

    count = pull_pr_feedback(repo, branch, sdlc_home(project_dir) / "feedback", phase)
    click.echo(f"ingested: {count} comment(s) → .sdlc/feedback/{phase}.md")


@github.command("setup")
def github_setup():
    """Full GitHub setup: labels, project board, workflows, and phase issues."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")

    if not repo:
        console.print("[red]No repo in spec.yaml — set repo: owner/repo first.[/red]")
        sys.exit(1)
    if not gh.is_available():
        console.print("[red]gh CLI not found or not authenticated.[/red]")
        sys.exit(1)

    project_name = spec.get("project_name", project_dir.name)
    wf = WorkflowState(project_dir)

    # Labels
    console.print("  Creating labels...")
    created = gh.setup_labels(repo)
    console.print(f"  [green]✓[/green] {len(created)} label(s) ready")

    # Project board
    project_info = wf.github_project
    if project_info:
        console.print(f"  [dim]Board #{project_info.get('number')} already exists — skipped[/dim]")
    else:
        console.print("  Creating project board...")
        project_info = gh.create_project_board(project_name, repo)
        if not project_info:
            console.print("  [yellow]Project board creation failed — check gh auth scope (project).[/yellow]")
        else:
            wf.set_github_project(project_info)
            wf.save()
            console.print(
                f"  [green]✓[/green] Board #{project_info['number']} · "
                f"{len(project_info.get('status_options', {}))} status columns"
            )

    # Workflow automations
    if project_info and project_info.get("node_id"):
        console.print("  Enabling workflow automations...")
        enabled = gh.enable_project_workflows(project_info["node_id"])
        if enabled:
            console.print(f"  [green]✓[/green] Workflows: {', '.join(enabled)}")
        else:
            console.print("  [dim]Workflows may already be enabled or require manual setup in GitHub UI.[/dim]")

    # Epic issue
    if wf.github_epic_issue:
        console.print(f"  [dim]Epic #{wf.github_epic_issue} already exists — skipped[/dim]")
    else:
        console.print("  Creating epic issue...")
        epic_body = (
            f"**{project_name}**\n\n{spec.get('description', '')}\n\n"
            f"This epic tracks all SDLC phases for this project."
        )
        epic_number = gh.create_epic(repo, project_name, epic_body)
        if epic_number:
            wf.set_github(epic_issue=epic_number)
            console.print(f"  [green]✓[/green] Epic #{epic_number}")
        else:
            console.print("  [yellow]Epic creation failed — continuing[/yellow]")

    # Phase issues
    console.print("  Creating phase issues...")
    phases = [
        ("requirement",    "[sdlc:requirement] Requirements"),
        ("design",         "[sdlc:design] System Design"),
        ("planning",       "[sdlc:plan] Task Plan"),
        ("implementation", "[sdlc:implementation] Implementation"),
        ("testing",        "[sdlc:testing] Testing & Validation"),
        ("review",         "[sdlc:review] Code Review"),
    ]
    for phase, title in phases:
        if wf.github_phase_items.get(phase):
            continue
        info = gh.create_phase_issue(
            repo=repo, phase=phase, title=title,
            body=f"Tracks the **{phase}** phase of {project_name}.\n\nArtifact will be linked when this phase begins.",
            project_info=project_info,
        )
        if info.get("number"):
            wf.set_phase_item(phase, info["number"], info.get("item_id", ""))
            console.print(f"  [green]✓[/green] #{info['number']} {title}")

    console.print("\n[bold green]GitHub setup complete.[/bold green]")
    if project_info:
        console.print(
            f"  Board: https://github.com/orgs/{repo.split('/')[0]}/projects/{project_info['number']}"
        )


@github.command("sync-board")
def github_sync_board():
    """Move the active phase issue to the correct board column based on current state."""
    from sdlc_orchestrator.integrations import github as gh

    STATE_BOARD: dict[str, tuple[str, str]] = {
        "requirement_in_progress":        ("In Progress",     "requirement"),
        "requirement_ready_for_approval": ("Awaiting Review", "requirement"),
        "design_in_progress":             ("In Progress",     "design"),
        "awaiting_design_approval":       ("Awaiting Review", "design"),
        "task_plan_in_progress":          ("In Progress",     "planning"),
        "task_plan_ready":                ("Awaiting Review", "planning"),
        "feedback_incorporation":         ("In Progress",     ""),
        "blocked":                        ("Blocked",         ""),
        "done":                           ("Done",            ""),
    }

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)
    project_info = wf.github_project

    if not repo or not project_info:
        click.echo("skipped: no repo or project board configured")
        return

    closed = gh.close_merged_pr_issues(
        repo=repo,
        story_items=wf.github_story_items,
        task_items=wf.github_task_items,
        project_info=project_info,
    )
    if closed:
        click.echo(f"auto-closed merged stories: {', '.join(closed)}")

    board_status, phase = STATE_BOARD.get(wf.state.value, ("In Progress", ""))

    def _ensure_phase_on_board(item: dict, p: str) -> str:
        item_id = item.get("item_id", "")
        issue_number = item.get("issue")
        if not item_id and issue_number and project_info:
            node_id = gh._get_issue_node_id(repo, issue_number)
            if node_id:
                item_id = gh.add_to_project(project_info["node_id"], node_id)
                if item_id:
                    wf.set_phase_item(p, issue_number, item_id)
                    click.echo(f"added #{issue_number} to board")
        return item_id

    def _ensure_story_on_board(story_id: str, item: dict) -> str:
        item_id = item.get("item_id", "")
        issue_number = item.get("number") or item.get("issue")
        if not item_id and issue_number and project_info:
            node_id = gh._get_issue_node_id(repo, issue_number)
            if node_id:
                item_id = gh.add_to_project(project_info["node_id"], node_id)
                if item_id:
                    wf.set_story_items({story_id: {"number": issue_number, "item_id": item_id}})
                    click.echo(f"added #{issue_number} ({story_id}) to board")
        return item_id

    if wf.state.value == "done":
        for p, item in wf.github_phase_items.items():
            item_id = _ensure_phase_on_board(item, p)
            if item_id:
                gh.move_phase_issue(project_info, item_id, "Done")
            if item.get("issue"):
                gh.close_issue(repo, item["issue"], comment="Closed automatically — SDLC workflow complete.")
        for story_id, item in wf.github_story_items.items():
            item_id = _ensure_story_on_board(story_id, item)
            if item_id:
                gh.move_phase_issue(project_info, item_id, "Done")
            issue_number = item.get("number") or item.get("issue")
            if issue_number:
                gh.close_issue(repo, issue_number, comment=f"Closed automatically — {story_id} complete.")
        for task_id, item in wf.github_task_items.items():
            issue_number = item.get("number") or item.get("issue")
            if issue_number:
                gh.close_issue(repo, issue_number, comment=f"Closed automatically — {task_id} complete.")
        click.echo("synced: all phases and stories → Done, issues closed")
        return

    if wf.state.value in ("story_in_progress", "story_awaiting_review"):
        story_board_status = "In Progress" if wf.state.value == "story_in_progress" else "Awaiting Review"
        current = wf.current_story
        if not current:
            click.echo("skipped: no current_story set (run 'sdlc story start STORY-NNN' first)")
            return
        story_item = wf.github_story_items.get(current, {})
        item_id = _ensure_story_on_board(current, story_item)
        if not item_id:
            click.echo(f"skipped: no board item for {current}")
            return
        ok = gh.move_phase_issue(project_info, item_id, story_board_status)
        click.echo(f"{'synced' if ok else 'failed'}: {current} → {story_board_status}")
        return

    if not phase:
        click.echo(f"skipped: no phase mapped for state {wf.state.value}")
        return

    item = wf.github_phase_items.get(phase, {})
    item_id = _ensure_phase_on_board(item, phase)
    if not item_id:
        click.echo(f"skipped: no board item for phase {phase} (run 'sdlc github setup' first)")
        return

    ok = gh.move_phase_issue(project_info, item_id, board_status)
    click.echo(f"{'synced' if ok else 'failed'}: {phase} → {board_status}")


@github.command("close-merged")
def github_close_merged():
    """Close story + task issues whose PR branch is merged."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    closed = gh.close_merged_pr_issues(
        repo=repo,
        story_items=wf.github_story_items,
        task_items=wf.github_task_items,
        project_info=wf.github_project,
    )
    click.echo(f"closed: {', '.join(closed)}" if closed else "no merged story PRs found")


@github.command("create-task-issues")
@click.argument("plan_file", default="docs/sdlc/plan.md")
def github_create_task_issues(plan_file):
    """Parse plan.md and create one GitHub issue per task, added to the board."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    plan_path = project_dir / plan_file
    if not plan_path.exists():
        click.echo(f"error: plan file not found at {plan_file}", err=True)
        sys.exit(1)

    tasks = gh.parse_plan_tasks(plan_path.read_text())
    if not tasks:
        click.echo("no tasks found in plan.md")
        return

    new_tasks = [t for t in tasks if t["id"] not in wf.github_task_items]
    if not new_tasks:
        click.echo(f"all {len(tasks)} task issues already exist")
        return

    console.print(f"  Creating {len(new_tasks)} task issue(s)...")
    created = gh.create_task_issues(
        repo=repo, tasks=new_tasks,
        project_info=wf.github_project,
        epic_issue=wf.github_epic_issue,
    )
    wf.set_task_items(created)
    for task_id, info in created.items():
        console.print(f"  [green]✓[/green] #{info['number']} {task_id}")
    click.echo(f"created: {len(created)} issue(s)")


@github.command("create-story-issues")
@click.argument("plan_file", default="docs/sdlc/plan.md")
def github_create_story_issues(plan_file):
    """Parse plan.md and create one GitHub issue per STORY-NNN, added to the board."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    wf = WorkflowState(project_dir)

    if not repo:
        click.echo("skipped: no repo configured")
        return

    plan_path = project_dir / plan_file
    if not plan_path.exists():
        click.echo(f"error: plan file not found at {plan_file}", err=True)
        sys.exit(1)

    stories = gh.parse_plan_stories(plan_path.read_text())
    if not stories:
        click.echo("no stories found in plan.md (add # STORY-NNN: Title sections)")
        return

    new_stories = [s for s in stories if s["id"] not in wf.github_story_items]
    if not new_stories:
        click.echo(f"all {len(stories)} story issues already exist")
        return

    console.print(f"  Creating {len(new_stories)} story issue(s)...")
    phase_story_count = len([p for p in wf.github_phase_items if wf.github_phase_items[p].get("issue")])
    created = gh.create_story_issues(
        repo=repo, stories=new_stories,
        project_info=wf.github_project,
        epic_issue=wf.github_epic_issue,
        story_number_offset=phase_story_count,
        task_issue_map=wf.github_task_items,
    )
    wf.set_story_items(created)
    for story_id, info in created.items():
        console.print(f"  [green]✓[/green] #{info['number']} {story_id}")
    click.echo(f"created: {len(created)} story issue(s)")


@github.command("close-phase-issue")
@click.argument("phase")
@click.option("--comment", default="", help="Optional closing comment")
def github_close_phase_issue(phase, comment):
    """Close the GitHub issue for a completed phase."""
    from sdlc_orchestrator.integrations import github as gh

    project_dir = require_project()
    repo = _get_repo(project_dir)
    wf = WorkflowState(project_dir)
    item = wf.github_phase_items.get(phase, {})
    issue_number = item.get("issue")
    if not issue_number:
        click.echo(f"skipped: no issue found for phase {phase}")
        return
    gh.close_issue(repo, issue_number, comment=comment or f"Phase {phase} complete.")
    click.echo(f"closed: #{issue_number} ({phase})")
