from __future__ import annotations

import subprocess
import sys
from pathlib import Path
import re

import click

from sdlc_orchestrator.state_machine import Phase
from sdlc_orchestrator.state_machine import WorkflowState
from sdlc_orchestrator.memory import MemoryManager
from sdlc_orchestrator.utils import sdlc_home
from sdlc_orchestrator.commands import require_project


@click.group()
def github():
    """GitHub operations. Called by Claude during /sdlc-orchestrate."""
    pass


def _get_repo(project_dir: Path) -> str:
    repo = MemoryManager(project_dir).spec().get("repo", "")
    if not repo:
        click.echo("No repo in spec.yaml", err=True)
        sys.exit(1)
    return repo


def _pr_number(url: str | None) -> int | None:
    if not url:
        return None
    match = re.search(r"/pull/(\d+)", url)
    return int(match.group(1)) if match else None


def _branch_commits(project_dir: Path, base: str, branch: str) -> list[str]:
    result = subprocess.run(
        ["git", "rev-list", "--reverse", f"{base}..{branch}"],
        cwd=project_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


@github.command("create-pr")
@click.argument("branch")
@click.argument("phase")
def github_create_pr(branch, phase):
    """Create a GitHub PR for the current phase branch."""
    from sdlc_orchestrator.integrations.github import create_pr, get_pr_number

    project_dir = require_project()
    repo = _get_repo(project_dir)
    spec = MemoryManager(project_dir).spec()
    project_name = spec.get("project_name", project_dir.name)
    subprocess.run(["git", "push", "-u", "origin", branch], cwd=project_dir, capture_output=True)

    wf = WorkflowState(project_dir)
    from sdlc_orchestrator.utils import get_active_project
    active = get_active_project(project_dir)
    default_base = f"worktree/{active}" if active else "main"
    base = wf._data.get("base_branch", default_base)

    url = create_pr(
        repo=repo, phase=phase, branch=branch,
        project_name=project_name,
        base=base,
        body=(
            f"## SDLC Phase: `{phase}`\n\n"
            f"Automated output. Review then approve.\n\n"
            f"> Generated by /sdlc-orchestrate"
        ),
    )
    pr_number = _pr_number(url) or get_pr_number(repo, branch)
    commits = _branch_commits(project_dir, base, branch)
    if pr_number or commits:
        item_phase = Phase.IMPLEMENTATION.value if phase.startswith("STORY-") else phase
        wf.set_work_item_links(phase, phase=item_phase, github_pr=pr_number, commits=commits)
    click.echo(url or "PR creation skipped (may already exist)")


@github.command("create-issue")
@click.argument("title")
@click.argument("body_file", required=False)
def github_create_issue(title, body_file):
    """Create a GitHub issue. Body read from file or stdin."""
    from sdlc_orchestrator.integrations.github import create_child_issue

    project_dir = require_project()
    repo = _get_repo(project_dir)

    if body_file and Path(body_file).exists():
        body = Path(body_file).read_text()
    elif not sys.stdin.isatty():
        body = sys.stdin.read()
    else:
        body = title

    issue_num = create_child_issue(repo, title, body)
    click.echo(f"issue: {issue_num or 'failed'}")


@github.command("pr-status")
@click.argument("branch")
def github_pr_status(branch):
    """Check if the PR for a branch is approved or merged."""
    from sdlc_orchestrator.integrations.github import get_pr_status

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("no-repo")
        sys.exit(0)

    click.echo(get_pr_status(repo, branch) or "not-found")


@github.command("ingest-feedback")
@click.argument("branch")
@click.argument("phase")
def github_ingest_feedback(branch, phase):
    """Pull PR review comments into .sdlc/feedback/<phase>.md."""
    from sdlc_orchestrator.integrations.github import pull_pr_feedback

    project_dir = require_project()
    spec = MemoryManager(project_dir).spec()
    repo = spec.get("repo", "")
    if not repo:
        click.echo("skipped: no repo configured")
        return

    count = pull_pr_feedback(repo, branch, sdlc_home(project_dir) / "feedback", phase)
    click.echo(f"ingested: {count} comment(s) → .sdlc/feedback/{phase}.md")
