"""
3-layer memory manager.

  Layer 1 — global.md   : coding values, DoD, review rules (machine-wide)
  Layer 2 — project.md  : stack, architecture, domain language, constraints
  Layer 3 — state.json  : execution memory (current state, tasks, decisions)

CLAUDE.md is generated by merging layers 1 + 2 and is what the agent reads.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional
import yaml


GLOBAL_MEMORY_PATH = Path.home() / ".config" / "sdlc-orchestrator" / "global.md"


class MemoryManager:
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir
        self.memory_dir = project_dir / "memory"
        self.memory_dir.mkdir(parents=True, exist_ok=True)

    # ── layer paths ──────────────────────────────────────────────────────────

    @property
    def global_path(self) -> Path:
        return GLOBAL_MEMORY_PATH

    @property
    def project_path(self) -> Path:
        return self.memory_dir / "project.md"

    @property
    def claude_md_path(self) -> Path:
        return self.project_dir / "CLAUDE.md"

    # ── readers ──────────────────────────────────────────────────────────────

    def global_memory(self) -> str:
        return self.global_path.read_text() if self.global_path.exists() else ""

    def project_memory(self) -> str:
        return self.project_path.read_text() if self.project_path.exists() else ""

    def spec(self) -> dict:
        spec_path = self.project_dir / "spec.yaml"
        if spec_path.exists():
            return yaml.safe_load(spec_path.read_text()) or {}
        return {}

    def feedback(self, phase: str) -> str:
        fb = self.project_dir / "feedback" / f"{phase}.md"
        if fb.exists():
            content = fb.read_text().strip()
            return f"\n## Feedback from previous iteration\n{content}\n" if content else ""
        return ""

    def artifact(self, name: str) -> str:
        """Load a named artifact (requirements, design, plan, ...)."""
        path = self.project_dir / "workflow" / "artifacts" / f"{name}.md"
        return path.read_text() if path.exists() else ""

    def execution_log(self, phase: str) -> str:
        """Last Claude output for this phase — used as resume context."""
        log = self.project_dir / "workflow" / "logs" / f"{phase}.log"
        if not log.exists():
            return ""
        text = log.read_text()
        # Trim to last 4000 chars to avoid overly long prompts
        return text[-4000:] if len(text) > 4000 else text

    # ── writers ──────────────────────────────────────────────────────────────

    def write_project_memory(self, content: str) -> None:
        self.project_path.write_text(content)
        self.regenerate_claude_md()

    def append_feedback(self, phase: str, text: str) -> None:
        fb_dir = self.project_dir / "feedback"
        fb_dir.mkdir(exist_ok=True)
        fb_file = fb_dir / f"{phase}.md"
        with fb_file.open("a") as f:
            from datetime import datetime, timezone
            ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
            f.write(f"\n### {ts}\n{text}\n")

    def write_artifact(self, name: str, content: str) -> Path:
        artifacts_dir = self.project_dir / "workflow" / "artifacts"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        path = artifacts_dir / f"{name}.md"
        path.write_text(content)
        return path

    def regenerate_claude_md(self) -> None:
        """Merge global.md + project.md → CLAUDE.md (what the agent reads)."""
        parts: list[str] = []

        global_mem = self.global_memory()
        if global_mem:
            parts.append("# Global Rules\n\n" + global_mem.strip())

        project_mem = self.project_memory()
        if project_mem:
            parts.append("# Project Context\n\n" + project_mem.strip())

        spec = self.spec()
        if spec:
            import yaml as _yaml
            parts.append("# Project Spec\n\n```yaml\n" + _yaml.dump(spec, default_flow_style=False) + "```")

        merged = "\n\n---\n\n".join(parts)
        self.claude_md_path.write_text(
            "<!-- AUTO-GENERATED by sdlc — edit memory/global.md or memory/project.md, not this file -->\n\n"
            + merged + "\n"
        )

    # ── context builder (injected into skill prompts) ─────────────────────

    def build_context(self, phase: str, extra_artifacts: Optional[list[str]] = None) -> str:
        """Build the {{MEMORY}} block injected into every skill prompt."""
        spec = self.spec()
        lines: list[str] = [
            f"## Project: {spec.get('project_name', 'Unknown')}",
            f"Tech stack: {spec.get('tech_stack', 'Unknown')}",
            "",
            "## Global Rules",
            self.global_memory() or "(none)",
            "",
            "## Project Context",
            self.project_memory() or "(none)",
        ]

        for artifact_name in (extra_artifacts or []):
            content = self.artifact(artifact_name)
            if content:
                lines += ["", f"## {artifact_name.replace('_', ' ').title()}", content]

        feedback = self.feedback(phase)
        if feedback:
            lines += ["", feedback]

        prior_log = self.execution_log(phase)
        if prior_log:
            lines += [
                "",
                "## Prior execution log (resume context — do not repeat completed work)",
                prior_log,
            ]

        return "\n".join(lines)
