"""
Shared utilities: SDLC home resolution and symlink management.

State directory layout (one worktree = one SDLC project):
  project-worktree/
    .sdlc/
      spec.yaml
      memory/
      workflow/
      feedback/
    CLAUDE.md               ← gitignored, regenerated by sdlc init
    AGENT.md                ← gitignored, regenerated by sdlc init

  ~/.sdlc/projects/<slug>  ← symlink → project-worktree/

Project identity is derived from the worktree directory name (project_slug).
Whether a project is done is read from .sdlc/workflow/state.json.
"""
from __future__ import annotations

import re
from pathlib import Path

def project_slug(project_dir: Path) -> str:
    """Stable slug derived from the project directory name."""
    name = project_dir.resolve().name
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


def get_active_project(project_dir: Path) -> str:
    """Return the project slug for this worktree (derived from directory name)."""
    return project_slug(project_dir)


def list_projects(project_dir: Path) -> list[str]:
    """Return project slugs visible from this directory."""
    names: set[str] = set()
    if (project_dir / ".sdlc" / "spec.yaml").exists():
        names.add(project_slug(project_dir))

    worktree_dir = project_dir / "worktree"
    if worktree_dir.exists():
        for child in worktree_dir.iterdir():
            if child.is_dir() and (child / ".sdlc" / "spec.yaml").exists():
                names.add(project_slug(child))

    return sorted(names)


def sdlc_home(project_dir: Path) -> Path:
    """Return the SDLC state directory for this worktree: project_dir/.sdlc/"""
    direct = project_dir / ".sdlc"
    direct.mkdir(parents=True, exist_ok=True)
    return direct


def create_symlink(project_dir: Path) -> Path:
    """Create ~/.sdlc/projects/<slug>  →  project worktree root."""
    slug = project_slug(project_dir)
    link = Path.home() / ".sdlc" / "projects" / slug
    link.parent.mkdir(parents=True, exist_ok=True)

    if link.is_symlink():
        link.unlink()
    elif link.exists():
        return link

    link.symlink_to(project_dir.resolve())
    return link


def find_project_dir(start: Path | None = None) -> Path | None:
    """Walk up from start (default: cwd) looking for a project root (.sdlc/ marker).
    Stops at home directory — never treats ~ as a project root."""
    home = Path.home().resolve()
    p = (start or Path.cwd()).resolve()
    for candidate in [p, *p.parents]:
        if candidate == home:
            break
        if (candidate / ".sdlc").is_dir():
            return candidate
    return None


def update_gitignore(project_dir: Path) -> None:
    """Add SDLC entries to .gitignore (idempotent)."""
    entries = [
        "CLAUDE.md",
        "AGENTS.md",
        "AGENT.md",
        ".claude/",
        ".codex/",
        ".kiro/",
        ".sdlc/",
        ".sdlc/.venv/",
        "worktree/",
    ]
    gi = project_dir / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    to_add = [e for e in entries if e not in existing]
    if to_add:
        with gi.open("a") as f:
            f.write("\n# SDLC orchestrator\n")
            for e in to_add:
                f.write(e + "\n")
