"""
Shared utilities: SDLC home resolution and symlink management.

State directory layout (multi-project):
  project-repo/
    .sdlc/
      active                ← name of the active project (plain text)
      projects/
        <name>/             ← one dir per project
          spec.yaml
          memory/
          workflow/
          feedback/
    CLAUDE.md               ← gitignored, regenerated by sdlc init
    AGENT.md                ← gitignored, regenerated by sdlc init

  ~/.sdlc/projects/<slug>-<name>  ← symlink → project-repo/.sdlc/projects/<name>/
"""
from __future__ import annotations

import os
import re
from pathlib import Path

_DEFAULT_PROJECT = "default"


def project_slug(project_dir: Path) -> str:
    """Stable slug derived from the project directory name."""
    name = project_dir.resolve().name
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


def _projects_dir(project_dir: Path) -> Path:
    return project_dir / ".sdlc" / "projects"


def get_active_project(project_dir: Path) -> str:
    """Return the name of the active project, defaulting to 'default'."""
    active_file = project_dir / ".sdlc" / "active"
    if active_file.exists():
        name = active_file.read_text().strip()
        if name:
            return name
    return _DEFAULT_PROJECT


def set_active_project(project_dir: Path, name: str) -> None:
    """Write the active project name."""
    (project_dir / ".sdlc").mkdir(parents=True, exist_ok=True)
    (project_dir / ".sdlc" / "active").write_text(name)


def list_projects(project_dir: Path) -> list[str]:
    """Return sorted list of project names that have a spec.yaml."""
    pd = _projects_dir(project_dir)
    if not pd.exists():
        return []
    return sorted(
        d.name for d in pd.iterdir()
        if d.is_dir() and (d / "spec.yaml").exists()
    )


def sdlc_home(project_dir: Path, project_name: str | None = None) -> Path:
    """
    Return the SDLC state directory for the active (or named) project.
    Layout: project_dir/.sdlc/projects/<name>/
    Falls back to legacy project_dir/.sdlc/ if no projects/ subdir exists yet.
    """
    name = project_name or get_active_project(project_dir)
    candidate = _projects_dir(project_dir) / name
    # Legacy layout: .sdlc/ directly (single-project repos)
    if not candidate.exists() and not (_projects_dir(project_dir)).exists():
        legacy = project_dir / ".sdlc"
        if legacy.exists():
            return legacy
    candidate.mkdir(parents=True, exist_ok=True)
    return candidate


def create_symlink(project_dir: Path, project_name: str | None = None) -> Path:
    """
    Create ~/.sdlc/projects/<slug>-<name>  →  project_dir/.sdlc/projects/<name>/
    """
    name = project_name or get_active_project(project_dir)
    sdlc_dir = sdlc_home(project_dir, name)

    slug = project_slug(project_dir)
    link_name = f"{slug}-{name}" if name != _DEFAULT_PROJECT else slug
    link = Path.home() / ".sdlc" / "projects" / link_name
    link.parent.mkdir(parents=True, exist_ok=True)

    if link.is_symlink():
        link.unlink()
    elif link.exists():
        return link

    link.symlink_to(sdlc_dir.resolve())
    return link


def find_project_dir(start: Path | None = None) -> Path | None:
    """Walk up from start (default: cwd) looking for a project root (.sdlc/ marker)."""
    p = (start or Path.cwd()).resolve()
    for candidate in [p, *p.parents]:
        if (candidate / ".sdlc").is_dir():
            return candidate
    return None


def update_gitignore(project_dir: Path) -> None:
    """Add SDLC entries to .gitignore (idempotent)."""
    entries = [
        "CLAUDE.md",
        "AGENTS.md",
        "AGENT.md",
        ".claude/",
        ".codex/",
        ".kiro/",
        ".sdlc/.venv/",
    ]
    gi = project_dir / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    to_add = [e for e in entries if e not in existing]
    if to_add:
        with gi.open("a") as f:
            f.write("\n# SDLC orchestrator\n")
            for e in to_add:
                f.write(e + "\n")
